let data = [
    {
      "show_id": 119,
      "type": "Movie",
      "title": "Gurgaon",
      "director": "Shanker Raman",
      "cast": "Akshay Oberoi, Pankaj Tripathi, Ragini Khanna, Aamir Bashir, Shalini Vatsa, Ashish Verma",
      "country": "India",
      "date_added": "September 2, 2021",
      "release_year": 2017,
      "rating": "TV-14",
      "duration": "106 min",
      "listed_in": "Dramas, International Movies, Thrillers",
      "description": "When the daughter of a wealthy family returns from college, she gets a frosty welcome from her brother, who has problems – and plans – of his own."
    },
    {
      "show_id": "s120",
      "type": "Movie",
      "title": "Here and There",
      "director": "JP Habac",
      "cast": "Janine Gutierrez, JC Santos, Victor Anastacio, Yesh Burce, Lotlot De Leon",
      "country": "",
      "date_added": "September 2, 2021",
      "release_year": 2020,
      "rating": "TV-MA",
      "duration": "99 min",
      "listed_in": "Dramas, International Movies, Romantic Movies",
      "description": "After meeting through a heated exchange on social media, two people with different backgrounds begin an online romance in the midst of a pandemic."
    },
    {
      "show_id": "s121",
      "type": "TV Show",
      "title": "Heroes of Goo Jit Zu",
      "director": "",
      "cast": "Jon Allen, Kellen Goff, Joe Hernandez, Kaiji Tang",
      "country": "Australia",
      "date_added": "September 2, 2021",
      "release_year": 2021,
      "rating": "TV-Y7",
      "duration": "1 Season",
      "listed_in": "Kids' TV, TV Comedies",
      "description": "After a meteor crash, a group of zoo animals transforms into squishy, gooey and stretchy superheroes with special powers and soon takes on evildoers."
    },
    {
      "show_id": "s122",
      "type": "TV Show",
      "title": "Hotel Del Luna",
      "director": "",
      "cast": "Lee Ji-eun, Yeo Jin-goo, Shin Jung-geun, Seo Yi-sook, Bae Hae-sun, Pyo Ji-hoon, Cho Hyun-chul, Kang Hong-suk, Lee Do-hyun, Lee Tae-seon, Kang Mina, Park You-na, Oh Ji-ho",
      "country": "",
      "date_added": "September 2, 2021",
      "release_year": 2019,
      "rating": "TV-14",
      "duration": "1 Season",
      "listed_in": "International TV Shows, Romantic TV Shows, TV Comedies",
      "description": "When he's invited to manage a hotel for dead souls, an elite hotelier gets to know the establishment's ancient owner and her strange world."
    },
    {
      "show_id": "s123",
      "type": "Movie",
      "title": "In the Cut",
      "director": "Jane Campion",
      "cast": "Meg Ryan, Mark Ruffalo, Jennifer Jason Leigh, Nick Damici, Sharrieff Pugh, Kevin Bacon, Yaani King Mondschein, Heather Litteer",
      "country": "United Kingdom, Australia, France, United States",
      "date_added": "September 2, 2021",
      "release_year": 2003,
      "rating": "R",
      "duration": "118 min",
      "listed_in": "Thrillers",
      "description": "After embarking on an affair with the cop probing the murder of a young woman, an insular schoolteacher suspects her lover was involved in the crime."
    },
    {
      "show_id": "s124",
      "type": "TV Show",
      "title": "Luv Kushh",
      "director": "",
      "cast": "",
      "country": "",
      "date_added": "September 2, 2021",
      "release_year": 2012,
      "rating": "TV-Y7",
      "duration": "1 Season",
      "listed_in": "Kids' TV",
      "description": "Based on the last book of the epic Ramayana, this series follows the endeavors and adventures of Lord Rama’s twin sons through their childhood."
    },
    {
      "show_id": "s125",
      "type": "TV Show",
      "title": "Pororo - The Little Penguin",
      "director": "",
      "cast": "",
      "country": "South Korea",
      "date_added": "September 2, 2021",
      "release_year": 2013,
      "rating": "TV-Y7",
      "duration": "3 Seasons",
      "listed_in": "Kids' TV, Korean TV Shows",
      "description": "On a tiny island, Pororo the penguin has fun adventures with his friends Eddy the fox, Loopy the beaver, Poby the polar bear and Crong the dinosaur."
    },
    {
      "show_id": "s126",
      "type": "TV Show",
      "title": "Q-Force",
      "director": "",
      "cast": "Sean Hayes, Wanda Sykes, Laurie Metcalf, David Harbour, Gary Cole, Patti Harrison, Matt Rogers",
      "country": "United States",
      "date_added": "September 2, 2021",
      "release_year": 2021,
      "rating": "TV-MA",
      "duration": "1 Season",
      "listed_in": "Crime TV Shows, TV Action & Adventure, TV Comedies",
      "description": "A gay superspy and his scrappy LGBTQ squad fight to prove themselves to the agency that underestimated them. Today, West Hollywood… tomorrow, the world!"
    },
    {
      "show_id": "s127",
      "type": "Movie",
      "title": "Shikara",
      "director": "Vidhu Vinod Chopra",
      "cast": "Aadil Khan, Sadia Khateeb, Zain Khan Durrani, Priyanshu Chatterjee, Bhavna Chauhan, Ashwin Dhar, Farid Azad Khan, Saghar Sehrai",
      "country": "India",
      "date_added": "September 2, 2021",
      "release_year": 2020,
      "rating": "TV-14",
      "duration": "115 min",
      "listed_in": "Dramas, International Movies, Romantic Movies",
      "description": "A couple must strive to remain resilient after regional hostilities drive them from their beloved home into a refugee camp."
    },
    {
      "show_id": "s128",
      "type": "Movie",
      "title": "A Cinderella Story",
      "director": "Mark Rosman",
      "cast": "Hilary Duff, Chad Michael Murray, Jennifer Coolidge, Dan Byrd, Regina King, Julie Gonzalo, Lin Shaye, Madeline Zima, Andrea Avery, Mary Pat Gleason, Paul Rodriguez, Whip Hubley, Kevin Kilner, Erica Hubbard, Simon Helberg",
      "country": "United States, Canada",
      "date_added": "September 1, 2021",
      "release_year": 2004,
      "rating": "PG",
      "duration": "95 min",
      "listed_in": "Children & Family Movies, Comedies",
      "description": "Teen Sam meets the boy of her dreams at a dance before returning to toil in her stepmother's diner. Can her lost cell phone bring them together?"
    },
    {
      "show_id": "s129",
      "type": "Movie",
      "title": "Agatha Christie's Crooked House",
      "director": "Gilles Paquet-Brenner",
      "cast": "Glenn Close, Terence Stamp, Max Irons, Gillian Anderson, Christina Hendricks, Stefanie Martini, Julian Sands, Honor Kneafsey, Christian McKay, Amanda Abbington",
      "country": "",
      "date_added": "September 1, 2021",
      "release_year": 2017,
      "rating": "PG-13",
      "duration": "115 min",
      "listed_in": "Dramas, International Movies, Thrillers",
      "description": "When a detective investigates the death of his ex-lover's grandfather, he uncovers secrets about the tycoon's manipulative family."
    },
    {
      "show_id": "s130",
      "type": "Movie",
      "title": "An Unfinished Life",
      "director": "Lasse Hallström",
      "cast": "Robert Redford, Jennifer Lopez, Morgan Freeman, Josh Lucas, Damian Lewis, Camryn Manheim, Becca Gardner, Lynda Boyd, Rob Hayter, P. Lynn Johnson",
      "country": "Germany, United States",
      "date_added": "September 1, 2021",
      "release_year": 2005,
      "rating": "PG-13",
      "duration": "108 min",
      "listed_in": "Dramas",
      "description": "A grieving widow and her daughter move in with her estranged father-in-law in Wyoming, where time allows them to heal and forgive."
    },
    {
      "show_id": 238,
      "type": "Movie",
      "title": "Boomika (Hindi)",
      "director": "Rathindran R Prasad",
      "cast": "Aishwarya Rajesh, Vidhu, Surya Ganapathy, Madhuri, Pavel Navageethan, Avantika Vandanapu",
      "country": "",
      "date_added": "August 23, 2021",
      "release_year": 2021,
      "rating": "TV-14",
      "duration": "122 min",
      "listed_in": "Horror Movies, International Movies, Thrillers",
      "description": "Paranormal activity at a lush, abandoned property alarms a group eager to redevelop the site, but the eerie events may not be as unearthly as they think."
    },
    {
      "show_id": "s239",
      "type": "Movie",
      "title": "Boomika (Malayalam)",
      "director": "Rathindran R Prasad",
      "cast": "Aishwarya Rajesh, Vidhu, Surya Ganapathy, Madhuri, Pavel Navageethan, Avantika Vandanapu",
      "country": "",
      "date_added": "August 23, 2021",
      "release_year": 2021,
      "rating": "TV-14",
      "duration": "122 min",
      "listed_in": "Horror Movies, International Movies, Thrillers",
      "description": "Paranormal activity at a lush, abandoned property alarms a group eager to redevelop the site, but the eerie events may not be as unearthly as they think."
    },
    {
      "show_id": "s240",
      "type": "Movie",
      "title": "Boomika (Telugu)",
      "director": "Rathindran R Prasad",
      "cast": "Aishwarya Rajesh, Vidhu, Surya Ganapathy, Madhuri, Pavel Navageethan, Avantika Vandanapu",
      "country": "",
      "date_added": "August 23, 2021",
      "release_year": 2021,
      "rating": "TV-14",
      "duration": "122 min",
      "listed_in": "Horror Movies, International Movies, Thrillers",
      "description": "Paranormal activity at a lush, abandoned property alarms a group eager to redevelop the site, but the eerie events may not be as unearthly as they think."
    },
    {
      "show_id": "s241",
      "type": "Movie",
      "title": "The Witcher: Nightmare of the Wolf",
      "director": "Han Kwang Il",
      "cast": "Theo James, Mary McDonnell, Lara Pulver, Graham McTavish, Tom Canton, David Errigo Jr, Jennifer Hale, Kari Wahlgren, Matt Yang King, Darryl Kurylo, Keith Ferguson",
      "country": "",
      "date_added": "August 23, 2021",
      "release_year": 2021,
      "rating": "TV-MA",
      "duration": "84 min",
      "listed_in": "Action & Adventure, Anime Features",
      "description": "Escaping from poverty to become a witcher, Vesemir slays monsters for coin and glory, but when a new menace rises, he must face the demons of his past."
    },
    {
      "show_id": "s242",
      "type": "TV Show",
      "title": "Manifest",
      "director": "",
      "cast": "Melissa Roxburgh, Josh Dallas, Athena Karkanis, J.R. Ramirez, Luna Blaise, Jack Messina, Parveen Kaur",
      "country": "United States",
      "date_added": "August 21, 2021",
      "release_year": 2021,
      "rating": "TV-14",
      "duration": "3 Seasons",
      "listed_in": "TV Dramas, TV Mysteries, TV Sci-Fi & Fantasy",
      "description": "When a plane mysteriously lands years after takeoff, the people onboard return to a world that has moved on without them and face strange, new realities."
    },
    {
      "show_id": "s243",
      "type": "TV Show",
      "title": "Comedy Premium League",
      "director": "",
      "cast": "",
      "country": "",
      "date_added": "August 20, 2021",
      "release_year": 2021,
      "rating": "TV-MA",
      "duration": "1 Season",
      "listed_in": "International TV Shows, TV Comedies",
      "description": "With satirical sketches, cheeky debates and blistering roasts, 16 of India’s wittiest entertainers compete in teams to be named the ultimate comedy champs."
    },
    {
      "show_id": "s244",
      "type": "TV Show",
      "title": "Everything Will Be Fine",
      "director": "",
      "cast": "Lucía Uribe, Flavio Medina, Isabella Vazquez Morales, Pierre Louis, Mercedes Hernández",
      "country": "",
      "date_added": "August 20, 2021",
      "release_year": 2021,
      "rating": "TV-MA",
      "duration": "1 Season",
      "listed_in": "International TV Shows, Spanish-Language TV Shows, TV Comedies",
      "description": "A separated couple live together for their child's sake in this satirical dramedy about what it means to be a good parent and spouse in today's world."
    },
    {
      "show_id": "s245",
      "type": "Movie",
      "title": "Gunshot",
      "director": "Karim El Shenawy",
      "cast": "Ahmed El Fishawy, Ruby, Mohamed Mamdouh, Ahmed Malek, Asmaa Abulyazeid, Samy Maghawry, Safaa El-Toukhy, Ahmed Kamal, Arfa Abdel Rassoul, Hana Shiha",
      "country": "",
      "date_added": "August 20, 2021",
      "release_year": 2018,
      "rating": "TV-14",
      "duration": "96 min",
      "listed_in": "Dramas, International Movies, Thrillers",
      "description": "After a clash at a protest ends in bloodshed, a forensic doctor and a journalist embark on a search for the elusive truth."
    },
    {
      "show_id": "s246",
      "type": "TV Show",
      "title": "Korean Cold Noodle Rhapsody",
      "director": "",
      "cast": "Paik Jong-won",
      "country": "",
      "date_added": "August 20, 2021",
      "release_year": 2021,
      "rating": "TV-PG",
      "duration": "1 Season",
      "listed_in": "Docuseries, International TV Shows",
      "description": "Refreshing and flavorful, naengmyeon is Korea's coolest summertime staple. A journey through its history begins, from how it's cooked to how it's loved."
    },
    {
      "show_id": "s247",
      "type": "Movie",
      "title": "Man in Love",
      "director": "Yin Chen-hao",
      "cast": "Roy Chiu, Ann Hsu, Tsai Chen-nan, Chung Hsin-ling, Lan Wei-hua, Peace Yang, Huang Lu Tz-yin",
      "country": "",
      "date_added": "August 20, 2021",
      "release_year": 2021,
      "rating": "TV-MA",
      "duration": "115 min",
      "listed_in": "Dramas, International Movies, Romantic Movies",
      "description": "When he meets a debt-ridden woman who's caring for her ailing father, a debt collector with a heart of gold sets out to win her love."
    },
    {
      "show_id": "s248",
      "type": "Movie",
      "title": "Sweet Girl",
      "director": "Brian Andrew Mendoza",
      "cast": "Jason Momoa, Isabela Merced, Manuel Garcia-Rulfo, Amy Brenneman, Adria Arjona, Raza Jaffrey, Justin Bartha, Lex Scott Davis, Michael Raymond-James",
      "country": "United States",
      "date_added": "August 20, 2021",
      "release_year": 2021,
      "rating": "R",
      "duration": "110 min",
      "listed_in": "Action & Adventure, Dramas",
      "description": "He lost the love of his life to a pharmaceutical company's greed. Now his daughter is without a mother, and he's without justice. For now."
    },
    {
      "show_id": "s249",
      "type": "TV Show",
      "title": "The Chair",
      "director": "",
      "cast": "Sandra Oh, Jay Duplass, Holland Taylor, David Morse, Bob Balaban, Nana Mensah, Everly Carganilla",
      "country": "",
      "date_added": "August 20, 2021",
      "release_year": 2021,
      "rating": "TV-MA",
      "duration": "1 Season",
      "listed_in": "TV Comedies, TV Dramas",
      "description": "At a major university, the first woman of color to become chair tries to meet the dizzying demands and high expectations of a failing English department."
    },
    {
      "show_id": "s250",
      "type": "Movie",
      "title": "The Loud House Movie",
      "director": "Dave Needham",
      "cast": "Asher Bishop, David Tennant, Michelle Gomez, Jill Talley, Brian Stepanek, Catherine Taber, Liliana Mumy, Nika Futterman, Cristina Pucelli, Jessica DiCicco, Grey Griffin, Lara Jill Miller",
      "country": "",
      "date_added": "August 20, 2021",
      "release_year": 2021,
      "rating": "TV-Y7",
      "duration": "88 min",
      "listed_in": "Children & Family Movies, Comedies, Music & Musicals",
      "description": "With his parents and all 10 sisters in tow, Lincoln Loud heads to Scotland and learns that royalty runs in the family in this global musical journey!"
    },
    {
      "show_id": "s251",
      "type": "Movie",
      "title": "A Faraway Land",
      "director": "Veronica Velasco",
      "cast": "Paolo Contis, Yen Santos, Hans Tórgarð, Ruby Ruiz, Zweden Obias, Maria Rianne Castro, Arianne Mavis Uera, Maricor Canlas",
      "country": "",
      "date_added": "August 19, 2021",
      "release_year": 2020,
      "rating": "TV-PG",
      "duration": "102 min",
      "listed_in": "Dramas, International Movies, Romantic Movies",
      "description": "In the Faroe Islands, a married woman meets a reporter filming a documentary on overseas Filipino workers, which soon sparks a complicated love story."
    },
    {
      "show_id": "s252",
      "type": "Movie",
      "title": "Like Crazy",
      "director": "Drake Doremus",
      "cast": "Anton Yelchin, Felicity Jones, Jennifer Lawrence, Charlie Bewley, Alex Kingston, Oliver Muirhead, Finola Hughes, Chris Messina, Ben York Jones, Jamie Thomas King",
      "country": "United States",
      "date_added": "August 19, 2021",
      "release_year": 2011,
      "rating": "PG-13",
      "duration": "91 min",
      "listed_in": "Dramas, Independent Movies, Romantic Movies",
      "description": "A spirited exchange student and an American man fall in love in LA. But their romance faces an uphill battle when she is forced to return to England."
    },
    {
      "show_id": "s253",
      "type": "Movie",
      "title": "Black Island",
      "director": "Miguel Alexandre",
      "cast": "Philip Froissant, Alice Dwyer, Hanns Zischler, Mercedes Müller, Sammy Scheuritzel, Lieselotte Voß, Katharina Schütz, Jodie Leslie Ahlborn, Marco Wittorf, Ilknur Boyraz",
      "country": "",
      "date_added": "August 18, 2021",
      "release_year": 2021,
      "rating": "TV-MA",
      "duration": "105 min",
      "listed_in": "International Movies, Thrillers",
      "description": "The dark secrets of a seemingly peaceful island threaten to swallow up an orphaned student when he grows close to a mysterious new teacher."
    },
    {
      "show_id": "s254",
      "type": "Movie",
      "title": "Bombay",
      "director": "Mani Ratnam",
      "cast": "Arvind Swamy, Manisha Koirala, Nasser, Raja Krishnamoorthy",
      "country": "India",
      "date_added": "August 18, 2021",
      "release_year": 1995,
      "rating": "TV-14",
      "duration": "135 min",
      "listed_in": "Dramas, International Movies, Romantic Movies",
      "description": "Years after they elope against their family’s wishes, a couple and their sons become caught in the throes of conflict in their city."
    },
    {
      "show_id": "s255",
      "type": "TV Show",
      "title": "Go! Go! Cory Carson",
      "director": "",
      "cast": "Alan C. Lim, Paul Killam, Maisie Benson, Kerry Gudjohnsen, Smith Foreman, Neena-Sinaii Simpo, Eli Morse, Adelaide Hirasaki, Jim Capobianco, Anna Chambers, Pfifer Chastain",
      "country": "United States",
      "date_added": "August 18, 2021",
      "release_year": 2021,
      "rating": "TV-Y",
      "duration": "5 Seasons",
      "listed_in": "Kids' TV",
      "description": "Beep, beep – go, go! Buckle up for fun and adventure with adorable kid car Cory Carson as he explores the winding roads of Bumperton Hills."
    },
    {
      "show_id": "s256",
      "type": "Movie",
      "title": "Memories of a Murderer: The Nilsen Tapes",
      "director": "Michael Harte",
      "cast": "",
      "country": "",
      "date_added": "August 18, 2021",
      "release_year": 2021,
      "rating": "TV-MA",
      "duration": "86 min",
      "listed_in": "Documentaries, International Movies",
      "description": "Serial killer Dennis Nilsen narrates his life and horrific crimes via a series of chilling audiotapes recorded from his jail cell."
    },
    {
      "show_id": "s257",
      "type": "Movie",
      "title": "Nneka The Pretty Serpent",
      "director": "Tosin Igho",
      "cast": "Idia Aisien, Ndidi Obi, Kenneth Okolie, Zack Orji, Bovi Ugboma, Bimbo Ademoye, Beverly Osu, Beverly Naya, Larry Gaaga, Shaffy Bello, Chioma Chukwuka Akpotha, Waje",
      "country": "",
      "date_added": "August 18, 2021",
      "release_year": 2020,
      "rating": "TV-14",
      "duration": "140 min",
      "listed_in": "Dramas, International Movies",
      "description": "Years after the mysterious murder of her parents, a traumatized woman gains supernatural powers that aid in her quest for revenge against the killers."
    },
    {
      "show_id": "s258",
      "type": "Movie",
      "title": "O Kadhal Kanmani",
      "director": "Mani Ratnam",
      "cast": "Dulquer Salmaan, Nithya Menon, Prakash Raj, Leela Samson, Vinodhini, Ramya Subramanian, Siva Ananth, John Devasahayam, Prabhu Lakshman",
      "country": "",
      "date_added": "August 18, 2021",
      "release_year": 2015,
      "rating": "TV-14",
      "duration": "133 min",
      "listed_in": "Dramas, International Movies, Romantic Movies",
      "description": "It's love at first sight for a young couple repelled by the concept of marriage, but their view shifts when they meet their older-couple neighbors."
    },
    {
      "show_id": "s259",
      "type": "Movie",
      "title": "Out of my league",
      "director": "Alice Filippi",
      "cast": "Ludovica Francesconi, Giuseppe Maggio, Gaja Masciale, Jozef Gjura, Eleonora Gaggero, Franco Ravera, Elisabetta Coraini, Michele Franco, Edoardo Rossi",
      "country": "",
      "date_added": "August 18, 2021",
      "release_year": 2020,
      "rating": "TV-MA",
      "duration": "92 min",
      "listed_in": "Comedies, Dramas, International Movies",
      "description": "Tired of swiping through the dating scene with her besties in tow, a charming yet awkward woman with a rare genetic disorder sets her sights on love."
    },
    {
      "show_id": "s260",
      "type": "Movie",
      "title": "Pahuna",
      "director": "Paakhi Tyrewala",
      "cast": "Anmol Limbu, Ishika Gurung, Manju Chettri, Banita Lagun, Binod Pradhan, Mahindra Bajgai, Rupa Tamang, Saran Rai",
      "country": "India, Nepal",
      "date_added": "August 18, 2021",
      "release_year": 2018,
      "rating": "TV-PG",
      "duration": "82 min",
      "listed_in": "Comedies, Dramas, International Movies",
      "description": "Fleeing unrest in their native Nepal, three young siblings separated from their parents must beat the odds to survive on their own in India."
    },
    {
      "show_id": "s261",
      "type": "TV Show",
      "title": "The Defeated",
      "director": "",
      "cast": "Taylor Kitsch, Nina Hoss, Logan Marshall-Green, Michael C. Hall, Tuppence Middleton, Mala Emde, Maximilian Ehrenreich, Sebastian Koch, Anne Ratte-Polle, Lena Dörrie, Benjamin Sadler",
      "country": "",
      "date_added": "August 18, 2021",
      "release_year": 2020,
      "rating": "TV-MA",
      "duration": "1 Season",
      "listed_in": "Crime TV Shows, International TV Shows, TV Dramas",
      "description": "In 1946 Berlin, an American cop searches for his missing brother while helping a novice German policewoman fight the violent crimes engulfing the city."
    },
    {
      "show_id": "s262",
      "type": "Movie",
      "title": "The Secret Diary of an Exchange Student",
      "director": "Bruno Garotti",
      "cast": "Larissa Manoela, Thati Lopes, Bruno Montaleone, David Sherod James, Maiara Walsh, Flávia Garrafa, Kathy-Ann Hart, Ray Faiola, Noa Graham",
      "country": "",
      "date_added": "August 18, 2021",
      "release_year": 2021,
      "rating": "TV-14",
      "duration": "97 min",
      "listed_in": "Comedies, International Movies, Romantic Movies",
      "description": "Looking to shake things up, two best friends embark on a life-changing adventure abroad as exchange students. But can they stay out of trouble?"
    },
    {
      "show_id": "s263",
      "type": "Movie",
      "title": "Untold: Deal With the Devil",
      "director": "Laura Brownson",
      "cast": "",
      "country": "",
      "date_added": "August 18, 2021",
      "release_year": 2021,
      "rating": "TV-MA",
      "duration": "78 min",
      "listed_in": "Documentaries, LGBTQ Movies, Sports Movies",
      "description": "Christy Martin broke boundaries and noses as she rose in the boxing world, but her public persona belied personal demons, abuse and a threat on her life."
    },
    {
      "show_id": "s264",
      "type": "TV Show",
      "title": "Mother Goose Club",
      "director": "",
      "cast": "",
      "country": "United States",
      "date_added": "August 16, 2021",
      "release_year": 2016,
      "rating": "TV-Y",
      "duration": "2 Seasons",
      "listed_in": "Kids' TV",
      "description": "Classic nursery rhymes and children's songs get a fresh twist in this high-energy program that helps kids learn as they dance and sing along."
    },
    {
      "show_id": "s265",
      "type": "Movie",
      "title": "Walk of Shame",
      "director": "Steve Brill",
      "cast": "Elizabeth Banks, James Marsden, Gillian Jacobs, Sarah Wright, Ethan Suplee, Bill Burr, Ken Davitian, Lawrence Gilliard Jr., Alphonso Mcauley, Da'Vone McDonald, John Marsden, Willie Garson, Oliver Hudson, P.J. Byrne",
      "country": "United States",
      "date_added": "August 16, 2021",
      "release_year": 2014,
      "rating": "R",
      "duration": "94 min",
      "listed_in": "Comedies, Independent Movies",
      "description": "After a night of boozy carousing, a local newscaster finds herself stranded on the streets of LA just hours before the job interview of a lifetime."
    },
    {
      "show_id": "s266",
      "type": "TV Show",
      "title": "Rascal Does Not Dream of Bunny Girl Senpai",
      "director": "",
      "cast": "Kaito Ishikawa, Asami Seto, Nao Toyama, Atsumi Tanezaki, Maaya Uchida, Yurika Kubo, Inori Minase",
      "country": "Japan",
      "date_added": "August 15, 2021",
      "release_year": 2018,
      "rating": "TV-14",
      "duration": "1 Season",
      "listed_in": "Anime Series, International TV Shows, Romantic TV Shows",
      "description": "After experiencing \"puberty syndrome\" himself, high school pariah Sakuta keeps meeting girls suffering from it, including his sister and actor Mai."
    },
    {
      "show_id": "s267",
      "type": "TV Show",
      "title": "The Creative Indians",
      "director": "",
      "cast": "",
      "country": "India",
      "date_added": "August 15, 2021",
      "release_year": 2020,
      "rating": "TV-MA",
      "duration": "1 Season",
      "listed_in": "Docuseries, International TV Shows",
      "description": "From chefs and comedians to filmmakers and fashion designers, India’s most notable imaginative minds share their artistic journeys."
    },
    {
      "show_id": "s268",
      "type": "Movie",
      "title": "The Piano",
      "director": "Jane Campion",
      "cast": "Holly Hunter, Harvey Keitel, Sam Neill, Anna Paquin, Kerry Walker, Genevieve Lemon, Tungia Baker, Ian Mune",
      "country": "New Zealand, Australia, France, United States",
      "date_added": "August 15, 2021",
      "release_year": 1993,
      "rating": "R",
      "duration": "121 min",
      "listed_in": "Classic Movies, Dramas, Independent Movies",
      "description": "With her daughter and her beloved piano in tow, a mute Scottish woman arrives in New Zealand, where a gruff loner sets out to seduce her."
    },
    {
      "show_id": "s269",
      "type": "Movie",
      "title": "Unroyal",
      "director": "Moses Inwang",
      "cast": "Matilda Lambert, Ik Ogbonna, Prince Sontoye, Blossom Chukwujekwu, Linda Osifo, Emem Inwang, Pete Edochie, Shaffy Bello, Okon Imeh  Bishop, Chinenye Nnebe, Femi Adebayo",
      "country": "",
      "date_added": "August 15, 2021",
      "release_year": 2020,
      "rating": "TV-MA",
      "duration": "97 min",
      "listed_in": "Dramas, International Movies",
      "description": "When a rude and arrogant princess finds herself relying on a gatekeeper after a terrible accident, it may be enough to make her change her ways."
    },
    {
      "show_id": "s270",
      "type": "TV Show",
      "title": "Winx Club",
      "director": "",
      "cast": "Liza Jacqueline, Helena Evangeliou, Lisa Ortiz, Kerry Williams, Gregory Abbey, Dan Green, Michael Sinterniklaas, Suzy Myers, Christina Rodriguez, Dani Schaffel, Sebastian Arcelus, Rachael Lillis",
      "country": "Italy",
      "date_added": "August 15, 2021",
      "release_year": 2015,
      "rating": "TV-Y7",
      "duration": "2 Seasons",
      "listed_in": "Kids' TV",
      "description": "In this animated fantasy, a girl named Bloom befriends a band of fairies, then follows them into the secretive and dangerous \"Magical Dimension."
    },
    {
      "show_id": "s271",
      "type": "Movie",
      "title": "Beckett",
      "director": "Ferdinando Cito Filomarino",
      "cast": "John David Washington, Boyd Holbrook, Alicia Vikander, Vicky Krieps, Lena Kitsopoulou, Panos Koronis, Maria Votti",
      "country": "Italy, Brazil, Greece",
      "date_added": "August 13, 2021",
      "release_year": 2021,
      "rating": "TV-MA",
      "duration": "110 min",
      "listed_in": "Action & Adventure",
      "description": "An American tourist goes on the run in Greece after a tragic accident plunges him into a political conspiracy that makes him a target for assassination."
    },
    {
      "show_id": "s272",
      "type": "TV Show",
      "title": "Brand New Cherry Flavor",
      "director": "",
      "cast": "Rosa Salazar, Eric Lange, Catherine Keener, Jeff Ward, Manny Jacinto, Hannah Levien, Patrick Fischler",
      "country": "United States",
      "date_added": "August 13, 2021",
      "release_year": 2021,
      "rating": "TV-MA",
      "duration": "1 Season",
      "listed_in": "TV Dramas, TV Horror, TV Mysteries",
      "description": "A filmmaker heads to Hollywood in the early '90s to make her movie but tumbles down a hallucinatory rabbit hole of sex, magic, revenge — and kittens."
    },
    {
      "show_id": "s273",
      "type": "TV Show",
      "title": "Fast & Furious Spy Racers",
      "director": "",
      "cast": "Tyler Posey, Charlet Chung, Jorge Diaz, Camille Ramsey, Luke Youngblood, Renée Elise Goldsberry",
      "country": "United States",
      "date_added": "August 13, 2021",
      "release_year": 2021,
      "rating": "TV-Y7",
      "duration": "5 Seasons",
      "listed_in": "Kids' TV",
      "description": "A government agency recruits teen driver Tony Toretto and his thrill-seeking friends to infiltrate a criminal street racing circuit as undercover spies."
    },
    {
      "show_id": 8764,
      "type": "Movie",
      "title": "WWII: Report from the Aleutians",
      "director": "John Huston",
      "cast": "",
      "country": "United States",
      "date_added": "March 31, 2017",
      "release_year": 1943,
      "rating": "TV-PG",
      "duration": "45 min",
      "listed_in": "Documentaries",
      "description": "Filmmaker John Huston narrates this Oscar-nominated World War II-era film about life among the U.S. soldiers protecting Alaska’s Aleutian Islands."
    }
  ]

  export default data;