FROM python:3.9.19

WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

COPY . .

CMD ["celery", "-A", "app.celery.tasks", "worker", "--loglevel=info"]
